version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=bddtest
      - MYSQL_USER=user
      - MYSQL_HOST=mysql

  web:
    build: .
    volumes:
      - ./:/var/www/
    ports:
      - 8080:80
